// ========================================
// This file is generated by T4, DO NOT MODIFY!
// 2016-02-21 18:08:34
// ========================================

using FYH.Cookbook.Model.Extensions;
using NHibernate.Mapping.Attributes;
using System;

namespace FYH.Cookbook.Model.DBEntity
{
    /// <summary>
    /// 
    /// </summary>
    [Class(0, Table = "Recipe")]
    [Cache(1, Usage = CacheUsage.ReadWrite)]
    public class Recipe
    {
        public const string TABLE_NAME = "Recipe";
        public const string COL_RECIPEID = "RecipeId";
        public const string COL_NAME = "Name";
        public const string COL_DESCRIPTION = "Description";
        public const string COL_DIRECTIONS = "Directions";
        public const string COL_ISDELETED = "IsDeleted";
        public const string COL_CREATEDDATE = "CreatedDate";

        /// <summary>
        /// 
        /// </summary>
        [Id(0, Name = "RecipeId", Column = "RecipeId", TypeType = typeof(int))]
        [Key(1)]
        [Generator(2, Class = "native")]
        public virtual int? RecipeId { get; set; }

        /// <summary>
        /// 
        /// </summary>
        [Property(NotNull = true, Length = 50)]
        public virtual string Name { get; set; }

        /// <summary>
        /// 
        /// </summary>
        [Property(Length = 2147483647)]
        public virtual string Description { get; set; }

        /// <summary>
        /// 
        /// </summary>
        [Property(Length = 2147483647)]
        public virtual string Directions { get; set; }

        /// <summary>
        /// 
        /// </summary>
        [Property(NotNull = true)]
        public virtual bool IsDeleted { get; set; }

        /// <summary>
        /// 
        /// </summary>
        [Property(NotNull = true)]
        public virtual DateTime CreatedDate { get; set; }
    }
}
