// ========================================
// This file is generated by T4, DO NOT MODIFY!
// 2016-02-21 18:08:34
// ========================================

using FYH.Cookbook.Model.Extensions;
using NHibernate.Mapping.Attributes;
using System;

namespace FYH.Cookbook.Model.DBEntity
{
    /// <summary>
    /// 
    /// </summary>
    [Class(0, Table = "RecipeTagMapping")]
    [Cache(1, Usage = CacheUsage.ReadWrite)]
    public class RecipeTagMapping
    {
        public const string TABLE_NAME = "RecipeTagMapping";
        public const string COL_MAPPINGID = "MappingId";
        public const string COL_RECIPEID = "RecipeId";
        public const string COL_TAGID = "TagId";

        /// <summary>
        /// 
        /// </summary>
        [Id(0, Name = "MappingId", Column = "MappingId", TypeType = typeof(int))]
        [Key(1)]
        [Generator(2, Class = "native")]
        public virtual int? MappingId { get; set; }

        /// <summary>
        /// 
        /// </summary>
        [Property(NotNull = true)]
        public virtual int RecipeId { get; set; }

        private Recipe _recipe = null;
        /// <summary>
        /// Foreign Key RecipeId Refer Recipe Entity Instance;
        /// </summary>
        [Core.Attributes.IgnoreConvertTypeScalar]
        public virtual Recipe Recipe { get { return _recipe ?? (_recipe = NHibernateExtension.GetEntityById<Recipe>(RecipeId)); } }

        /// <summary>
        /// 
        /// </summary>
        [Property(NotNull = true)]
        public virtual int TagId { get; set; }

        private Tag _tag = null;
        /// <summary>
        /// Foreign Key TagId Refer Tag Entity Instance;
        /// </summary>
        [Core.Attributes.IgnoreConvertTypeScalar]
        public virtual Tag Tag { get { return _tag ?? (_tag = NHibernateExtension.GetEntityById<Tag>(TagId)); } }
    }
}
