// ========================================
// This file is generated by T4, DO NOT MODIFY!
// 2016-02-21 18:08:34
// ========================================

using FYH.Cookbook.Model.Extensions;
using NHibernate.Mapping.Attributes;
using System;

namespace FYH.Cookbook.Model.DBEntity
{
    /// <summary>
    /// 
    /// </summary>
    [Class(0, Table = "Tag")]
    [Cache(1, Usage = CacheUsage.ReadWrite)]
    public class Tag
    {
        public const string TABLE_NAME = "Tag";
        public const string COL_TAGID = "TagId";
        public const string COL_NAME = "Name";
        public const string COL_DESCRIPTION = "Description";

        /// <summary>
        /// 
        /// </summary>
        [Id(0, Name = "TagId", Column = "TagId", TypeType = typeof(int))]
        [Key(1)]
        [Generator(2, Class = "native")]
        public virtual int? TagId { get; set; }

        /// <summary>
        /// 
        /// </summary>
        [Property(NotNull = true, Length = 50)]
        public virtual string Name { get; set; }

        /// <summary>
        /// 
        /// </summary>
        [Property(Length = 2147483647)]
        public virtual string Description { get; set; }
    }
}
